### ISSUE TITLE
Update Presets and Log levels to match the new spec

### ISSUE THREAD

**Issue by jacobminer** [steamclock/steamclog-android#83]
Table is [here](https://coda.io/d/Tech-Working-Group_dq8QHMnEi6A/Aug-16th-2021_suivT#Proposed-New-Presets_tulNM). We'll probably also need our projects to start changing all `verbose` to `debug`

**Comment by jenncoop** [comment]
Shayla has added our [Spec to Coda](https://coda.io/d/SteamcLog_dmRQYLbOZrl/API-Docs_sufrm)
